### ISSUE TITLE
Crashed when installed the app 1st time

### ISSUE THREAD

**Issue by shuvashish76** [mirfatif/PermissionManagerX#19]
FATAL EXCEPTION: main
Process: com.mirfatif.permissionmanagerx, PID: 1490
java.lang.IllegalArgumentException: reasonPhrase can't be empty.
	at android.webkit.WebResourceResponse.setStatusCodeAndReasonPhrase(WebResourceResponse.java:138)
	at android.webkit.WebResourceResponse.<init>(WebResourceResponse.java:76)
	at xq.a(SourceFile:292)
	at alW.handleMessage(SourceFile:67)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by mirfatif** [comment]
Thanks for reporting.

The crash occurs, when you open Help, due to a [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=925887) in "Android System WebView" package installed on your device. If its package name is `com.google.android.webview` you can simply update the package from Play Store to fix the problem. But if the package is `com.android.webview` you cannot update it unless your OEM releases an update for the device.
To address the latter case, we can add a workaround to the app provided that someone is available for testing. We don't have any device with the bug to test.

Related: https://t.me/PermissionManagerX/968

**Comment by mirfatif** [comment]
Fixed in https://github.com/mirfatif/PermissionManagerX/commit/88aa04ab38aaf664304a74b00a12df9aaad04732
